[package]
name = "sa6"
version = "0.1.0"
edition = "2021"




[dependencies]
chrono = "0.4.34"
actix-web = "4"
diesel = { version = "2.1.0", features = ["mysql"] }
dotenvy = "0.15"
serde = "1.0.197"
mysql = "24.0.0"
